name: iOS-ipa-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Flutter pub get
        run: flutter pub get

      - name: Setup iOS build environment
        run: |
          cd ios
          flutter build ios --no-codesign --debug
          cd ..

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir -p build/ios/iphoneos/Payload

      - name: Move app to Payload
        run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Create IPA file
        run: |
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload
          cd ../../..

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          body: |
            ## Run iOS App v${{ steps.version.outputs.version }}
            
            ### What's New
            - iOS IPA build for client ID input app
            - Built on: ${{ github.event.head_commit.timestamp }}
            - Commit: ${{ github.sha }}
            
            ### Installation
            Download the IPA file and install on your iOS device.
          draft: false
          prerelease: false

      - name: Upload IPA to Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: RunIOS-v${{ steps.version.outputs.version }}.ipa
          asset_content_type: application/octet-stream

      - name: Upload IPA as Artifact (for PRs)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: RunIOS-IPA
          path: build/ios/iphoneos/FlutterIpaExport.ipa 